framework: mocha
postMerge:
  pattern:
    - "./test/**/*.js"
  env:
    CI: true
preMerge:
  pattern:
    - "./test/**/*.js"
  env:
    CI: true
preRun:
     command:
        - yarn install
postRun:
     command:
        - yarn --version
version: 1.0
